export default {
    state:{
        list:[
            {
                'name':'基础',
                'url':'',
                'type':'title'
            },
            {
                'name':'安装',
                'url':'',
                'type':'subtitle',
                'child':[{
                    'name':'Vue Devtools',
                    'url':'/devtools',
                    'type':'link'
                },
                {
                    'name':'直接用script引入',
                    'url':'',
                    'type':'subtitle',
                    'child':[{
                        'name':'CDN',
                        'url':'',
                        'type':'link'
                    }]
                },
                {
                    'name':'NPM',
                    'url':'/npm',
                    'type':'link'
                },
                {
                    'name':'命令行工具',
                    'url':'/cmd',
                    'type':'link'
                },
                {
                    'name':'开发版本',
                    'url':'/deversion',
                    'type':'link'
                },
                {
                    'name':'Bower',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'AMD模块加载器',
                    'url':'/amd',
                    'type':'link'
                }]
            },{
                'name':'介绍',
                'url':'',
                'type':'link',
                'child':[{
                    'name':'Vue.js 是什么',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'起步',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'声明式渲染',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'条件与循环',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'处理用户输入',
                    'url':'',
                    'type':'link'
                },
                {
                    'name':'组件化应用构建',
                    'url':'',
                    'type':'link',
                    'child':[{
                        'name':'与自定义元素的关系',
                        'url':'',
                        'type':'link'
                    }]
                },
                {
                    'name':'准备好了吗',
                    'url':'',
                    'type':'link'
                }]
            },{
                'name':'Vue实例',
                'url':'',
                'type':'link'
            },{
                'name':'模板语法',
                'url':'',
                'type':'link'
            },{
                'name':'计算属性和侦听器',
                'url':'',
                'type':'link'
            },{
                'name':'过度&动画',
                'url':'',
                'type':'title'
            },{
                'name':'进入&离开',
                'url':'',
                'type':'link'
            },{
                'name':'状态过度',
                'url':'',
                'type':'link'
            },{
                'name':'可复用性&组合',
                'url':'',
                'type':'title'
            },{
                'name':'混入',
                'url':'',
                'type':'link'
            },{
                'name':'自定义指令',
                'url':'',
                'type':'link'
            },{
                'name':'工具',
                'url':'',
                'type':'title'
            },{
                'name':'生产环境部署',
                'url':'',
                'type':'link'
            },{
                'name':'规模化',
                'url':'',
                'type':'title'
            },{
                'name':'路由',
                'url':'',
                'type':'link'
            },{
                'name':'内在',
                'url':'',
                'type':'title'
            },{
                'name':'深入响应式原理',
                'url':'',
                'type':'link'
            },{
                'name':'迁移',
                'url':'',
                'type':'title'
            },{
                'name':'从Vue1.x迁移',
                'url':'',
                'type':'link'
            },{
                'name':'更多',
                'url':'',
                'type':'title'
            },{
                'name':'对比其他框架',
                'url':'',
                'type':'link'
            }
        ]
    }
}